extends Node


var data = {
	"guns": [
		{
			"name" : "Pistol",
			"frame": 0,
			"damage" : 30.0,
			"rate" : 2.2,
			"accuracy": 0.9,
			"velocity": 240,
			"lifetime": 2.4,
			"bullet" : 1,
			"magazine" : 9,
			"reloadTime" : 1.0,
			"shots" : 1,
			"splash" : false,
			"shots_fired" : 0,
			"eject_ammo" : true,
			"eject_mag":true,
			"sound" : "res://assets/sounds/pistol.ogg",
			"reload_sound" : "res://assets/sounds/reload.ogg"
		},	
		{
			"name" : "Laser Pistol",
			"frame": 1,
			"damage" : 50.0,
			"rate" : 1.6,
			"accuracy": 0.95,
			"velocity": 360,
			"lifetime": 1.2,
			"bullet" : 0,
			"magazine" : 5,
			"reloadTime" : 0.8,
			"shots" : 1,
			"splash" : false,
			"shots_fired" : 0,
			"eject_ammo" : false,
			"eject_mag":false,
			"sound" : "res://assets/sounds/laser.ogg",
			"reload_sound" : "res://assets/sounds/reload.ogg"
		},
		{
			"name" : "UZI",
			"frame": 4,
			"damage" : 3.0,
			"rate" : 30.0,
			"accuracy": 0.2,
			"velocity": 280,
			"lifetime": 0.8,
			"bullet" : 1,
			"magazine" : 30,
			"reloadTime" : 1.2,
			"shots" : 1,
			"splash" : false,
			"eject_ammo" : true,
			"eject_mag":true,
			"shots_fired" : 0,
			"sound" : "res://assets/sounds/pistol.ogg",
			"reload_sound" : "res://assets/sounds/reload.ogg"
		},
		{
			"name" : "Assault",
			"frame": 5,
			"damage" : 15.0,
			"rate" : 15.0,
			"accuracy": 0.5,
			"velocity": 280,
			"lifetime": 1.0,
			"bullet" : 1,
			"magazine" : 30,
			"reloadTime" : 1.4,
			"shots" : 1,
			"splash" : false,
			"eject_ammo" : true,
			"eject_mag":true,
			"shots_fired" : 0,
			"sound" : "res://assets/sounds/pistol.ogg",
			"reload_sound" : "res://assets/sounds/reload.ogg"
		},
		{
			"name" : "Shotgun",
			"frame": 2,
			"damage" : 10,
			"rate" : 2.0,
			"accuracy": 0.0,
			"velocity": 280,
			"lifetime": 0.6,
			"bullet" : 1,
			"magazine" : 6,
			"reloadTime" : 1.5,
			"shots" : 5,
			"splash" : false,
			"eject_ammo" : true,
			"eject_mag": false,
			"shots_fired" : 0,
			"sound" : "res://assets/sounds/pistol.ogg",
			"reload_sound" : "res://assets/sounds/reload.ogg"
		},
		{
			"name" : "Rocket Launcher",
			"frame": 6,
			"damage" : 120.0,
			"rate" : 1.1,
			"accuracy": 0.9,
			"velocity": 150,
			"lifetime": 2.0,
			"bullet" : 2,
			"magazine" : 2,
			"reloadTime" : 8.0,
			"shots" : 1,
			"splash" : true,
			"eject_ammo" : false,
			"eject_mag":false,
			"shots_fired" : 0,
			"sound" : "res://assets/sounds/pistol.ogg",
			"reload_sound" : "res://assets/sounds/reload.ogg"
		},
		{
			"name" : "Bow",
			"frame": 7,
			"damage" : 120.0,
			"rate" : 0.5,
			"accuracy": 0.9,
			"velocity": 90,
			"lifetime": 3.0,
			"bullet" : 3,
			"magazine" : 5,
			"reloadTime" : 2.0,
			"shots" : 1,
			"splash" : false,
			"eject_ammo" : false,
			"eject_mag":false,
			"shots_fired" : 0,
			"sound" : "res://assets/sounds/bow.ogg",
			"reload_sound" : "res://assets/sounds/empty.ogg"
		},
	]
}
var lobby = "https://mizjam.herokuapp.com"
var matchmaker = "wss://serene-falls-22766.herokuapp.com"
